#index:
#    path: /
#    controller: App\Controller\DefaultController::index
first_route:
  path: /home
  controller: App\Controller\HomeController::index
guides_routes:
  path: /guides
  controller: App\Controller\GuidesController::guides