#index:
#    path: /
#    controller: App\Controller\DefaultController::index
first_route:
  path: /home
  controller: App\Controller\HomeController::index
guides_routes:
  path: /guides
  controller: App\Controller\GuidesController::guides
articles_routes:
  path: /articles/{category}
  controller: App\Controller\ArticlesController::articles
user_route:
  path: /signin
  controller: App\Controller\SignInController::signin
backoffice_route:
    path: /backoffice
    controller: App\Controller\BackOfficeController::index
update_category_route:
    path: /updateCategory/{categoryId}
    controller: App\Controller\UpdateController::updateCategory
update_article_route:
    path: /updateArticle/{articleId}
    controller: App\Controller\UpdateController::updateArticle